# Generated by Django 4.1.7 on 2023-03-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('continent', models.CharField(max_length=25)),
                ('population', models.IntegerField()),
                ('capital', models.CharField(max_length=25)),
                ('surface', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('year_founded', models.IntegerField()),
                ('number_of_employees', models.IntegerField()),
                ('activity', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.countries')),
            ],
        ),
    ]
