# Generated by Django 4.1.7 on 2023-03-20 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_countries_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('review', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.countries')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.individuals')),
            ],
            options={
                'unique_together': {('individual', 'country')},
            },
        ),
        migrations.AddField(
            model_name='individuals',
            name='countries_visited',
            field=models.ManyToManyField(through='restapi.VisitedCountries', to='restapi.countries'),
        ),
    ]
