# Generated by Django 4.1.7 on 2023-03-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_alter_individuals_countries_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuals',
            name='countries_visited',
            field=models.ManyToManyField(through='restapi.VisitedCountries', to='restapi.countries'),
        ),
    ]
